[build]
  command = "yarn build"
  publish = "public"

[build.environment]
  NODE_VERSION = "22"

[build.processing]
  skip_processing = true

[[redirects]]
  from = "https://adamiz.mehmet.dev"
  to = "https://mehmet.adamizda.com"
  status = 301
  force = true
