[build]
  command = "yarn build"
  publish = "public"

[build.environment]
  NODE_VERSION = "22"

[build.processing]
  skip_processing = true

[[redirects]]
  from = "https://adamiz.mehmet.dev"
  to = "https://mehmet.adamizda.com"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "/index-tr.html"
  status = 200
  force = true
  conditions = { Language = ["tr"] }

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = true

